version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: weekly
    target-branch: "default"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: # Prevent Cargo.toml patch updates
          - version-update:semver-patch
    target-branch: "default"
